name = "ghcr.io/gaboose/raspios-lite:2025-05-13-bookworm"

[labels]
"org.opencontainers.image.source"="https://github.com/gaboose/pipod"

[platform.'linux/arm64'.labels]
"com.github.gaboose.pipod.source.url" = "https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2025-05-13/2025-05-13-raspios-bookworm-arm64-lite.img.xz"
"com.github.gaboose.pipod.source.sha256" = "62d025b9bc7ca0e1facfec74ae56ac13978b6745c58177f081d39fbb8041ed45"
"com.github.gaboose.pipod.source.partitions.import" = "sda2"

[platform.'linux/armhf'.labels]
"com.github.gaboose.pipod.source.url" = "https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2025-05-13/2025-05-13-raspios-bookworm-armhf-lite.img.xz"
"com.github.gaboose.pipod.source.sha256" = "a73d68b618c3ca40190c1aa04005a4dafcf32bc861c36c0d1fc6ddc48a370b6e"
"com.github.gaboose.pipod.source.partitions.import" = "sda2"